version: '2'

services:
  web:
    build:
      context: .
      target: react
  
  nginx:
    build:
      context: .
      target: nginx
    image: 'supernovabirth/memeor-web:latest'
    container_name: memeor-web
    ports:
      - "80:80"

  app:
    build:
      context: .
      target: spring-boot
    image: 'supernovabirth/memeor:latest'
    container_name: memeor-app
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mms_db
      - SPRING_DATASOURCE_USERNAME=mms-postgres
      - SPRING_DATASOURCE_PASSWORD=mms-postgres-password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mms_db
      - POSTGRES_USER=mms-postgres
      - POSTGRES_PASSWORD=mms-postgres-password
    volumes:
      - memeor-data:/var/lib/postgresql/data

volumes:
  memeor-data:
    driver: local